/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BetGetResponse model module.
 * @module model/BetGetResponse
 * @version 1.0
 */
class BetGetResponse {
    /**
     * Constructs a new <code>BetGetResponse</code>.
     * @alias module:model/BetGetResponse
     */
    constructor() { 
        
        BetGetResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BetGetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BetGetResponse} obj Optional instance to populate.
     * @return {module:model/BetGetResponse} The populated <code>BetGetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BetGetResponse();

            if (data.hasOwnProperty('dealersSecondCard')) {
                obj['dealersSecondCard'] = ApiClient.convertToType(data['dealersSecondCard'], 'String');
            }
            if (data.hasOwnProperty('dealerTotal')) {
                obj['dealerTotal'] = ApiClient.convertToType(data['dealerTotal'], 'Number');
            }
            if (data.hasOwnProperty('dealersAdditionalCard')) {
                obj['dealersAdditionalCard'] = ApiClient.convertToType(data['dealersAdditionalCard'], ['String']);
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} dealersSecondCard
 */
BetGetResponse.prototype['dealersSecondCard'] = undefined;

/**
 * @member {Number} dealerTotal
 */
BetGetResponse.prototype['dealerTotal'] = undefined;

/**
 * @member {Array.<String>} dealersAdditionalCard
 */
BetGetResponse.prototype['dealersAdditionalCard'] = undefined;

/**
 * @member {String} result
 */
BetGetResponse.prototype['result'] = undefined;






export default BetGetResponse;

