/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BetResponse model module.
 * @module model/BetResponse
 * @version 1.0
 */
class BetResponse {
    /**
     * Constructs a new <code>BetResponse</code>.
     * @alias module:model/BetResponse
     */
    constructor() { 
        
        BetResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BetResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BetResponse} obj Optional instance to populate.
     * @return {module:model/BetResponse} The populated <code>BetResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BetResponse();

            if (data.hasOwnProperty('card1')) {
                obj['card1'] = ApiClient.convertToType(data['card1'], 'String');
            }
            if (data.hasOwnProperty('card2')) {
                obj['card2'] = ApiClient.convertToType(data['card2'], 'String');
            }
            if (data.hasOwnProperty('dealersCard')) {
                obj['dealersCard'] = ApiClient.convertToType(data['dealersCard'], 'String');
            }
            if (data.hasOwnProperty('yourTotal')) {
                obj['yourTotal'] = ApiClient.convertToType(data['yourTotal'], 'Number');
            }
            if (data.hasOwnProperty('followActions')) {
                obj['followActions'] = ApiClient.convertToType(data['followActions'], ['String']);
            }
            if (data.hasOwnProperty('betId')) {
                obj['betId'] = ApiClient.convertToType(data['betId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} card1
 */
BetResponse.prototype['card1'] = undefined;

/**
 * @member {String} card2
 */
BetResponse.prototype['card2'] = undefined;

/**
 * @member {String} dealersCard
 */
BetResponse.prototype['dealersCard'] = undefined;

/**
 * @member {Number} yourTotal
 */
BetResponse.prototype['yourTotal'] = undefined;

/**
 * @member {Array.<String>} followActions
 */
BetResponse.prototype['followActions'] = undefined;

/**
 * @member {Number} betId
 */
BetResponse.prototype['betId'] = undefined;






export default BetResponse;

