/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BetRequest model module.
 * @module model/BetRequest
 * @version 1.0
 */
class BetRequest {
    /**
     * Constructs a new <code>BetRequest</code>.
     * @alias module:model/BetRequest
     */
    constructor() { 
        
        BetRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BetRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BetRequest} obj Optional instance to populate.
     * @return {module:model/BetRequest} The populated <code>BetRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BetRequest();

            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'Number');
            }
            if (data.hasOwnProperty('bet')) {
                obj['bet'] = ApiClient.convertToType(data['bet'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} playerId
 */
BetRequest.prototype['playerId'] = undefined;

/**
 * @member {Number} bet
 */
BetRequest.prototype['bet'] = undefined;






export default BetRequest;

