/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetPlayerResponse model module.
 * @module model/GetPlayerResponse
 * @version 1.0
 */
class GetPlayerResponse {
    /**
     * Constructs a new <code>GetPlayerResponse</code>.
     * @alias module:model/GetPlayerResponse
     */
    constructor() { 
        
        GetPlayerResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPlayerResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPlayerResponse} obj Optional instance to populate.
     * @return {module:model/GetPlayerResponse} The populated <code>GetPlayerResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPlayerResponse();

            if (data.hasOwnProperty('cash')) {
                obj['cash'] = ApiClient.convertToType(data['cash'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} cash
 */
GetPlayerResponse.prototype['cash'] = undefined;

/**
 * @member {String} name
 */
GetPlayerResponse.prototype['name'] = undefined;






export default GetPlayerResponse;

