/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HighscoreElementResponse model module.
 * @module model/HighscoreElementResponse
 * @version 1.0
 */
class HighscoreElementResponse {
    /**
     * Constructs a new <code>HighscoreElementResponse</code>.
     * @alias module:model/HighscoreElementResponse
     */
    constructor() { 
        
        HighscoreElementResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HighscoreElementResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HighscoreElementResponse} obj Optional instance to populate.
     * @return {module:model/HighscoreElementResponse} The populated <code>HighscoreElementResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HighscoreElementResponse();

            if (data.hasOwnProperty('pos')) {
                obj['pos'] = ApiClient.convertToType(data['pos'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('money')) {
                obj['money'] = ApiClient.convertToType(data['money'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} pos
 */
HighscoreElementResponse.prototype['pos'] = undefined;

/**
 * @member {String} name
 */
HighscoreElementResponse.prototype['name'] = undefined;

/**
 * @member {Number} money
 */
HighscoreElementResponse.prototype['money'] = undefined;






export default HighscoreElementResponse;

