/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HighscoreElementResponse from './HighscoreElementResponse';

/**
 * The HighscoreResponse model module.
 * @module model/HighscoreResponse
 * @version 1.0
 */
class HighscoreResponse {
    /**
     * Constructs a new <code>HighscoreResponse</code>.
     * @alias module:model/HighscoreResponse
     */
    constructor() { 
        
        HighscoreResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HighscoreResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HighscoreResponse} obj Optional instance to populate.
     * @return {module:model/HighscoreResponse} The populated <code>HighscoreResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HighscoreResponse();

            if (data.hasOwnProperty('highscores')) {
                obj['highscores'] = ApiClient.convertToType(data['highscores'], [HighscoreElementResponse]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/HighscoreElementResponse>} highscores
 */
HighscoreResponse.prototype['highscores'] = undefined;






export default HighscoreResponse;

