/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsuranceRequest model module.
 * @module model/InsuranceRequest
 * @version 1.0
 */
class InsuranceRequest {
    /**
     * Constructs a new <code>InsuranceRequest</code>.
     * @alias module:model/InsuranceRequest
     */
    constructor() { 
        
        InsuranceRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InsuranceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsuranceRequest} obj Optional instance to populate.
     * @return {module:model/InsuranceRequest} The populated <code>InsuranceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsuranceRequest();

            if (data.hasOwnProperty('insurance')) {
                obj['insurance'] = ApiClient.convertToType(data['insurance'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} insurance
 */
InsuranceRequest.prototype['insurance'] = undefined;






export default InsuranceRequest;

