/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StandResponse model module.
 * @module model/StandResponse
 * @version 1.0
 */
class StandResponse {
    /**
     * Constructs a new <code>StandResponse</code>.
     * @alias module:model/StandResponse
     */
    constructor() { 
        
        StandResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StandResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StandResponse} obj Optional instance to populate.
     * @return {module:model/StandResponse} The populated <code>StandResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StandResponse();

            if (data.hasOwnProperty('followActions')) {
                obj['followActions'] = ApiClient.convertToType(data['followActions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} followActions
 */
StandResponse.prototype['followActions'] = undefined;






export default StandResponse;

