/**
 * Blackjack Gaming Service
 * A REST API to play Blackjack. Written in C++ with oat++.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BlackjackGamingService);
  }
}(this, function(expect, BlackjackGamingService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BlackjackGamingService.BetResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BetResponse', function() {
    it('should create an instance of BetResponse', function() {
      // uncomment below and update the code to test BetResponse
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be.a(BlackjackGamingService.BetResponse);
    });

    it('should have the property card1 (base name: "card1")', function() {
      // uncomment below and update the code to test the property card1
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be();
    });

    it('should have the property card2 (base name: "card2")', function() {
      // uncomment below and update the code to test the property card2
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be();
    });

    it('should have the property dealersCard (base name: "dealersCard")', function() {
      // uncomment below and update the code to test the property dealersCard
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be();
    });

    it('should have the property yourTotal (base name: "yourTotal")', function() {
      // uncomment below and update the code to test the property yourTotal
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be();
    });

    it('should have the property followActions (base name: "followActions")', function() {
      // uncomment below and update the code to test the property followActions
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be();
    });

    it('should have the property betId (base name: "betId")', function() {
      // uncomment below and update the code to test the property betId
      //var instance = new BlackjackGamingService.BetResponse();
      //expect(instance).to.be();
    });

  });

}));
